### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by ggsnpdsn** [tsl0922/DD-WRT#4]
I did not compile successfully on ubuntu22.04, ubuntu18.06, ubuntu14.04, and debian11. Following the readme sequence, there are always errors in make configure, and different platforms have different errors。

on  ubuntu22.04，build stabridge，wrtbwmon and so on failed
eg：
mipsel-linux-uclibc-ar rc lib/libssp_nonshared.a obj/libssp_nonshared/__stack_chk_fail_local.o
mipsel-linux-uclibc-ranlib lib/libssp_nonshared.a
make[2]: Leaving directory '/home/fgghj/01-DD-WRT/DD-WRT/dd-wrt/src/router/musl'
[ ! -d wrtbwmon ] || make -C wrtbwmon configure
make[2]: Entering directory '/home/fgghj/01-DD-WRT/DD-WRT/dd-wrt/src/router/wrtbwmon'
make[2]: *** No rule to make target 'configure'.  Stop.
make[2]: Leaving directory '/home/fgghj/01-DD-WRT/DD-WRT/dd-wrt/src/router/wrtbwmon'
make[1]: [rules/all.mk:376: wrtbwmon-configure] Error 2 (ignored)
[ ! -d httpd ] || make -C httpd configure
make[2]: Entering directory '/home/fgghj/01-DD-WRT/DD-WRT/dd-wrt/src/router/httpd'
make[2]: *** No rule to make target 'configure'.  Stop.
make[2]: Leaving directory '/home/fgghj/01-DD-WRT/DD-WRT/dd-wrt/src/router/httpd'
make[1]: [rules/all.mk:376: httpd-configure] Error 2 (ignored)
[ ! -d configure ] || make -C configure
make[1]: Leaving directory '/home/fgghj/01-DD-WRT/DD-WRT/dd-wrt/src/router'

**Comment by tsl0922** [comment]
The upstream keep changes, it's normal that scripts and patches in this repo may break.

You may want to try an old version that compiled successful from [Actions](https://github.com/tsl0922/DD-WRT/actions) until it's fixed,  the latest successful version r53879.

**Comment by ggsnpdsn** [comment]
I'll give it a try, by the way, https://gitlab.com/egc112/ddwrt-community-build-clone Do you have operating instructions
