### ISSUE TITLE
Directly download the latest build successfully code without successfully compiling it

### ISSUE THREAD

**Issue by ggsnpdsn** [tsl0922/DD-WRT#5]
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --disable-nls
[ ! -d stabridge ] || make -C stabridge configure
make[2]: Entering directory '/home/hggh/01-DD-WRT/DD-WRT-20231104/dd-wrt/src/router/stabridge'
make[2]: *** No rule to make target 'configure'.  Stop.
make[2]: Leaving directory '/home/hggh/01-DD-WRT/DD-WRT-20231104/dd-wrt/src/router/stabridge'
make[1]: [rules/all.mk:376: stabridge-configure] Error 2 (ignored)
[ ! -d eop-tunnel ] || make -C eop-tunnel configure
make[2]: Entering directory '/home/hggh/01-DD-WRT/DD-WRT-20231104/dd-wrt/src/router/eop-tunnel'
make[2]: *** No rule to make target 'configure'.  Stop.
make[2]: Leaving directory '/home/hggh/01-DD-WRT/DD-WRT-20231104/dd-wrt/src/router/eop-tunnel'
make[1]: [rules/all.mk:376: eop-tunnel-configure] Error 2 (ignored)
cd iperf && libtoolize
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: linking file 'config/ltmain.sh'
libtoolize: You should add the contents of the following files to 'aclocal.m4':
libtoolize:   '/usr/share/aclocal/libtool.m4'
libtoolize:   '/usr/share/aclocal/ltoptions.m4'
libtoolize:   '/usr/share/aclocal/ltsugar.m4'
libtoolize:   '/usr/share/aclocal/ltversion.m4'
libtoolize:   '/usr/share/aclocal/lt~obsolete.m4'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
cd iperf && aclocal
cd iperf && autoconf
configure.ac:85: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
make[1]: *** [rules/iperf.mk:30: iperf-configure] Error 1
make[1]: Leaving directory '/home/hggh/01-DD-WRT/DD-WRT-20231104/dd-wrt/src/router'
make: *** [Makefile:132: configure] Error 2

-rw-rw-r--  1 hggh hggh 6373248 11月 22 13:21 20231104.tar.gz
drwxrwxr-x  9hggh hggh    4096 11月 22 13:22 DD-WRT-20231104

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy

**Comment by tsl0922** [comment]
The script in this repo will always checkout the latest did-wrt code (which is break now), you need to change the svn revision yourself.
